# Generated by Django 6.0.1 on 2026-02-03 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('row', models.CharField(choices=[('A', 'Row A (Electric)'), ('B', 'Row B'), ('C', 'Row C'), ('D', 'Row D'), ('E', 'Row E'), ('F', 'Row F (Electric)')], max_length=1)),
                ('number', models.IntegerField()),
                ('is_electric', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['row', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked In'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='parking.parkingspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'spot'],
                'unique_together': {('spot', 'date')},
            },
        ),
    ]
