# Generated by Django 6.0.1 on 2026-03-01 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["CONFIRMED", "CHECKED_IN"])),
                fields=("spot", "date"),
                name="uniq_active_reservation_per_spot_per_day",
            ),
        ),
    ]
