# Generated by Django 6.0.1 on 2026-03-01 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking", "0002_alter_reservation_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-date", "slot", "spot"]},
        ),
        migrations.RemoveConstraint(
            model_name="reservation",
            name="uniq_active_reservation_per_spot_per_day",
        ),
        migrations.AddField(
            model_name="reservation",
            name="slot",
            field=models.CharField(
                choices=[("AM", "Morning"), ("PM", "Afternoon")],
                default="AM",
                max_length=2,
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["CONFIRMED", "CHECKED_IN"])),
                fields=("spot", "date", "slot"),
                name="uniq_active_reservation_per_spot_per_date_slot",
            ),
        ),
    ]
