# Generated by Django 6.0.1 on 2026-03-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking", "0003_alter_reservation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("CONFIRMED", "Confirmed"),
                    ("CHECKED_IN", "Checked In"),
                    ("CANCELLED", "Cancelled"),
                    ("EXPIRED", "Expired (No check-in)"),
                ],
                default="CONFIRMED",
                max_length=20,
            ),
        ),
    ]
