# Generated by Django 6.0.1 on 2026-03-01 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking", "0004_alter_reservation_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reservation",
            name="uniq_active_reservation_per_spot_per_date_slot",
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["CONFIRMED", "CHECKED_IN"])),
                fields=("user", "date", "slot"),
                name="uniq_active_reservation_per_user_per_date_slot",
            ),
        ),
    ]
